package com.example.duan1_pro1121.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class MyHelper extends SQLiteOpenHelper {

    public static String DB_NAME = "SOCCER_MANAGEMENT";
    public static int VERSION = 1;

    public MyHelper(@Nullable Context context) {
        super(context, DB_NAME, null,VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE IF NOT EXISTS MANAGER(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                "ACCOUNT TEXT UNIQUE,NAME TEXT,POSITION TEXT,PASSWORD TEXT,SALARY INTEGER,BANKNUMBER TEXT,BANKNAME TEXT)");
        db.execSQL("CREATE TABLE IF NOT EXISTS CUSTOMER(ID INTEGER PRIMARY KEY AUTOINCREMENT," +
                "ACCOUNT TEXT UNIQUE,NAME TEXT,PHONE TEXT,ADDRESS TEXT,MONEY INTEGER,PASSWORD TEXT,IMG BLOD)");
        db.execSQL("CREATE TABLE IF NOT EXISTS PITCH_CATEGORIES(ID PRIMARY KEY AUTOINCREMENT,NAME TEXT,MONEY INTEGER)");
        db.execSQL("CREATE TABLE IF NOT EXISTS PITCH(ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT UNIQUE," +
                "CATEGORY_ID INTEGER REFERENCES PITCH_CATEGORIES,STATUS INTEGER)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ORDERS(ID INTEGER PRIMARY KEY AUTOINCREMENT,MANAGER_ID INTEGER REFERENCES MANAGER" +
                ",CUSTOMER_ID INTEGER REFERENCES CUSTOMER,PITCH_ID INTEGER REFERENCES PITCH,START_TIME TEXT," +
                "END_TIME TEXT,TOTAL INTEGER,DATE TEXT,STATUS INTEGER)");
        db.execSQL("CREATE TABLE IF NOT EXISTS SERVICE(ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,MONEY INTEGER,COUNT INTEGER)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ORDER_DETAILS(ID INTEGER PRIMARY KEY AUTOINCREMENT,ID_ORDER INTEGER REFERENCES ORDERS,ID_SERVICE INTEGER REFERENCES SERVICE)");

        db.execSQL("INSERT INTO PITCH_CATEGORIES(NAME,MONEY) VALUES ('SÂN 5',70000)");
        db.execSQL("INSERT INTO PITCH_CATEGORIES(NAME,MONEY) VALUES ('SÂN 7',100000)");
        db.execSQL("INSERT INTO PITCH_CATEGORIES(NAME,MONEY) VALUES ('SÂN 11',120000)");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS ORDER_DETAILS");
        db.execSQL("DROP TABLE IF EXISTS ORDERS");
        db.execSQL("DROP TABLE IF EXISTS SERVICE");
        db.execSQL("DROP TABLE IF EXISTS PITCH");
        db.execSQL("DROP TABLE IF EXISTS PITCH_CATEGORIES");
        db.execSQL("DROP TABLE IF EXISTS MANAGER");
        db.execSQL("DROP TABLE IF EXISTS CUSTOMER");

        onCreate(db);
    }
}
